### ISSUE TITLE
Running Tensorflow notebook getting error

### ISSUE THREAD

**Issue by Pupinin** [Microsoft/AzureML-BERT#2]
When running the notebook I'm getting this error at "Submit and Monitor your run" section. The Status of the experiment is 'Failed'.

It started out OK and went to status 'Running' but after a while this error is presented. 
Can someone point met in the right direction? 
I just don't understand where to look for a solution. I'm new to Azure Machine Learning and don't understand the "amlcompute" reference in the errormessage.

----------------------------------

Extracting pretrained model...
Start to download GLUE dataset...

Downloading and extracting CoLA...
	Completed!
Downloading and extracting SST...
	Completed!
Processing MRPC...
Traceback (most recent call last):
  File "download_glue_data.py", line 137, in <module>
    sys.exit(main(sys.argv[1:]))
  File "download_glue_data.py", line 129, in main
    format_mrpc(args.data_dir, args.path_to_mrpc)
  File "download_glue_data.py", line 61, in format_mrpc
    urllib.request.urlretrieve(MRPC_TRAIN, mrpc_train_file)
  File "/azureml-envs/azureml_d830dfb29fc815326bc8cd6e3a484d0b/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/azureml-envs/azureml_d830dfb29fc815326bc8cd6e3a484d0b/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/azureml-envs/azureml_d830dfb29fc815326bc8cd6e3a484d0b/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/azureml-envs/azureml_d830dfb29fc815326bc8cd6e3a484d0b/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/azureml-envs/azureml_d830dfb29fc815326bc8cd6e3a484d0b/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/azureml-envs/azureml_d830dfb29fc815326bc8cd6e3a484d0b/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/azureml-envs/azureml_d830dfb29fc815326bc8cd6e3a484d0b/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

The experiment failed. Finalizing run...
Logging experiment finalizing status in history service
Cleaning up all outstanding Run operations, waiting 300.0 seconds
1 items cleaning up...
Cleanup took 0.10145998001098633 seconds

Error occurred: Compute target amlcompute is in state deleting and thus not ready for runs.

**Comment by davidefiocco** [comment]
It looks like `download_glue_data.py` failed when downloading the MRPC dataset. If that fails, you want be able to execute the rest. Have you retried this? I didn't myself, but maybe there were issues with the hosting/accessibility of the data files at the time you attempted the download?

**Comment by xiaoyongzhu** [comment]
Sorry for this - We've just fixed the issue. Can you re-run it and let us know how it goes?

**Comment by davidefiocco** [comment]
(for reference the fix is this: https://github.com/Microsoft/AzureML-BERT/commit/b905b2dd251dca01fb2fdb3ee63bac28257cb47d#diff-3356639d4d1e0982f20115c3ee9925fc)

**Comment by Pupinin** [comment]
> Sorry for this - We've just fixed the issue. Can you re-run it and let us know how it goes?

Yes! Thank you the experiment works now.

**Comment by AmerAlsabbagh** [comment]
I am facing a similar issue now. I submit my experiment and it runs but after it finishes.
it started out OK and went to status 'Running' but after a while (when the threads finished and we are in post processing and job clean up) this error is presented. I get 
"Compute target amlcompute is in state deleting and thus not ready for runs."
