### ISSUE TITLE
Initializing BertMultiTask  model error

### ISSUE THREAD

**Issue by nigaregr** [microsoft/AzureML-BERT#25]
Hi, I am getting the following error when I run Bert pretraining:
09/09/2019 10:13:43 - INFO - logger -   Vocabulary contains 30522 tokens
09/09/2019 10:13:43 - INFO - logger -   Initializing BertMultiTask model
Traceback (most recent call last):
  File "AzureML-BERT/pretrain/PyTorch/train_nitin.py", line 361, in <module>
    summary_writer = summary_writer)
  File "/home/nigaregr/Documents/AzureML-BERT/pretrain/PyTorch/models.py", line 121, in __init__
    self.network.register_batch(BatchType.PRETRAIN_BATCH, "pretrain_dataset", loss_calculation=BertPretrainingLoss(self.bert_encoder, bert_config))
  File "/home/nigaregr/Documents/AzureML-BERT/pretrain/PyTorch/models.py", line 25, in __init__
    self.cls = BertPreTrainingHeads(config, self.bert.embeddings.word_embeddings.weight)
TypeError: __init__() takes 2 positional arguments but 3 were given

**Comment by skaarthik** [comment]
Are you using pytorch-pretrained-bert package v0.6.2?

**Comment by nigaregr** [comment]
Yes. That fixes it. Thanks
